# Generated by Django 5.2.6 on 2025-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('collected', 'Collected')], default='pending', max_length=10),
        ),
    ]
