# Generated by Django 5.2.4 on 2026-02-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
